### ISSUE TITLE
右边那一列动画执行没左边一列好

### ISSUE THREAD

**Issue by ChenDeZhi-QYan** [xiongchenf/flybus#1]
右边那一排动画执行没左边一列好,  点击右边的产品的时候的加入效果飘出去右边那里,感觉像是飘到第三列的样子

**Comment by hzpeng57** [comment]
计算第三个点的横坐标应该是前两个点和的1/2，不是差的1/2

**Comment by xiongchenf** [comment]
是topPoint['x']的计算有误，需要加上x坐标较小的点的x的值
