### ISSUE TITLE
发现两个小bug

### ISSUE THREAD

**Issue by hzpeng57** [xiongchenf/flybus#3]
### 1、多次点击会报错。 ###
解决办法：在执行startAnimation之前先判断上次的动画是否执行完毕，如果没有则不执行这个动画。

### 2、第三个点的横坐标x计算有误 ###
解决办法： 应该取前两个点横坐标和的1/2，而不是差的1/2.

**Comment by wuhhhh** [comment]
设置全局变量isAnimate:false；
当 isAnimate 为true表示正在动画，无法点击
当isAnimate 为false表示执行完毕，可以进行下一次动画
touchOnGoods: function (e) {
    var isAnimate = this.data.isAnimate;
    if (isAnimate) {
      return ;
    }
    this.setData({
      isAnimate: true
    })
    this.finger = {}; var topPoint = {};
    this.finger['x'] = e.touches["0"].clientX;
    this.finger['y'] = e.touches["0"].clientY;
    if (this.finger['y'] < this.busPos['y']) { 
      topPoint['y'] = this.finger['y'] - 150;
    } else {
      topPoint['y'] = this.busPos['y'] - 150;
    }
    topPoint['x'] = Math.abs(this.finger['x'] + this.busPos['x']) / 2;
    this.linePos = app.bezier([this.finger, topPoint, this.busPos], 30);
    this.startAnimation();
  },
  startAnimation: function () {
    var index = 0, that = this,
      bezier_points = that.linePos['bezier_points'];
    this.setData({
      hide_good_box: false,
      bus_x: that.finger['x'],
      bus_y: that.finger['y']
    })
    this.timer = setInterval(function () {
      index++;
      that.setData({
        bus_x: bezier_points[index]['x'],
        bus_y: bezier_points[index]['y']
      })
      if (index >= 28) {
        clearInterval(that.timer);
        that.setData({
          hide_good_box: true,
          hideCount: false,
          count: that.data.count += 1,
          isAnimate:false
        })
      }
    }, 33);
  }

**Comment by xiongchenf** [comment]
已修复
